{% set name = "qcengine" %}
{% set version = "0.5.1" %}
{% set sha256 = "0d70a463859a5e15c74b1ba32e7d746a5ac59d8c624c9b545ca943fc06214d5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: QCEngine-{{ version }}.tar.gz
  url: https://github.com/MolSSI/QCEngine/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pyyaml
    - py-cpuinfo
    - psutil

test:
  imports:
    - pytest
    - qcengine
  requires:
    - pytest
  commands:
    - py.test --pyargs qcengine

about:
  home: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.'

  doc_url: https://qcengine.readthedocs.io/en/latest/
  dev_url: http://github.com/MolSSI/QCEngine

extra:
  recipe-maintainers:
    - dgasmith
