travis:
  secure:
    BINSTAR_TOKEN: Mc4L2pFusH5XkmdXEQ2z6WIBf/JUVcFHq1I/iE61E9kvco7rPLy58Z7tkxBiXyCGO9NCVrAKnDwsEXO3JGJlS0vbqCifrlPRWvyzGlpowUerGMyO3ag53oyWkuWKD+cXt+gi+cIUbM9ljR0R/TM3uiue136mejW8HADCDJs3WYvqiiQwEQYgkhvFym/WtxtyEJk6ACg0/8VkW3DATi1pJV8ZdiwSD5v6mTaABtuLzQQ5HQbF5tBj2V7tqZageJX0C+xpqcDG7cxqLMxCZfeFORFXNF8R0551eEbVq+QVpG1fZRSs/jGUd4HLKTU5aeNMvuP9Gli5WrcFosiHa3xkJXkUmzBgkam7k6BQYcBLf2oui9QUv37MxQEgJR3m1a9aP9VDDP3s4up9zKNU0vngz8vdgZT9HCG4e0YAmFwJNdqX3OShgHGe6i625gEF2H+7JDXyYQnW+rxllGUGpPwG/yX5JjrUOskZA3xKIL+qxgKwVg7LBJWF3/fpeGaPVm7oYM0+j0PsQz7wtdRYXLYFHgDXTpKlhLPLOxtRYX+ztCcpbRk+Cbv0MJXLER5/aGdwa8+MfDzlLMIAIJwaVKmY63eJJmfBAHZGSCIAlkSZ2H/014Fc/pXSz/B9wPcpnDp86pcqUJtg0zzUSJzZ/pnZJg37YydG01GoXycUrYNVlKM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
